[package]
name = "xcm-simulator"
version = "0.9.9"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test kit to simulate cross-chain message passing and XCM execution"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
paste = "1.0.5"

frame-support = { git = "https://github.com/compound-finance/substrate", branch = "gateway" }
sp-io = { git = "https://github.com/compound-finance/substrate", branch = "gateway" }
sp-std = { git = "https://github.com/compound-finance/substrate", branch = "gateway" }

xcm = { path = "../" }
xcm-executor = { path = "../xcm-executor" }
polkadot-core-primitives = { path = "../../core-primitives"}
polkadot-parachain = { path = "../../parachain" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
